# Generated by Django 5.2.3 on 2024-01-01 12:00:00

import uuid
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Data source name', max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('redis', 'Redis'), ('api', 'External API')], help_text='Type of data source', max_length=50)),
                ('table_name', models.CharField(blank=True, help_text='PostgreSQL table name', max_length=100)),
                ('query_template', models.TextField(blank=True, help_text='Query template for data retrieval')),
                ('cache_ttl', models.IntegerField(default=3600, help_text='Cache TTL in seconds')),
                ('is_active', models.BooleanField(default=True, help_text='Whether data source is active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Source',
                'verbose_name_plural': 'Data Sources',
                'db_table': 'whatsapp_data_sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_name', models.CharField(help_text='Template name in ACS', max_length=100, unique=True)),
                ('template_id', models.CharField(help_text='Template ID from ACS', max_length=100, unique=True)),
                ('language', models.CharField(default='es', help_text='Template language code', max_length=10)),
                ('category', models.CharField(choices=[('donations', 'Donations'), ('ministry', 'Ministry Contact'), ('events', 'Event Information'), ('general', 'General')], default='general', help_text='Template category for organization', max_length=50)),
                ('parameters', models.JSONField(default=list, help_text='List of required parameters')),
                ('is_active', models.BooleanField(default=True, help_text='Whether template is active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Template',
                'verbose_name_plural': 'WhatsApp Templates',
                'db_table': 'whatsapp_templates',
                'ordering': ['category', 'template_name'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text="User's phone number", max_length=20, unique=True)),
                ('context_data', models.JSONField(default=dict, help_text='Conversation context data')),
                ('last_interaction', models.DateTimeField(default=django.utils.timezone.now, help_text='Last interaction time')),
                ('session_start', models.DateTimeField(default=django.utils.timezone.now, help_text='Session start time')),
                ('is_active', models.BooleanField(default=True, help_text='Whether session is active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Context',
                'verbose_name_plural': 'WhatsApp Contexts',
                'db_table': 'whatsapp_contexts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text="User's phone number", max_length=20)),
                ('message_text', models.TextField(help_text='Incoming message from user')),
                ('intent_detected', models.CharField(blank=True, help_text='Detected user intent', max_length=100)),
                ('response_text', models.TextField(help_text='Response sent to user')),
                ('response_id', models.CharField(blank=True, help_text='ACS response ID', max_length=100)),
                ('parameters_used', models.JSONField(default=dict, help_text='Parameters injected into template')),
                ('fallback_used', models.BooleanField(default=False, help_text='Whether OpenAI fallback was used')),
                ('processing_time_ms', models.FloatField(default=0.0, help_text='Response processing time')),
                ('success', models.BooleanField(default=True, help_text='Whether interaction was successful')),
                ('error_message', models.TextField(blank=True, help_text='Error message if interaction failed')),
                ('context_data', models.JSONField(default=dict, help_text='Additional context data')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('template_used', models.ForeignKey(blank=True, help_text='Template used for response', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='whatsapp_bot.whatsapptemplate')),
            ],
            options={
                'verbose_name': 'WhatsApp Interaction',
                'verbose_name_plural': 'WhatsApp Interactions',
                'db_table': 'whatsapp_interactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='whatsappinteraction',
            index=models.Index(fields=['phone_number'], name='whatsapp_in_phone_n_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappinteraction',
            index=models.Index(fields=['created_at'], name='whatsapp_in_created_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappinteraction',
            index=models.Index(fields=['template_used'], name='whatsapp_in_templat_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappinteraction',
            index=models.Index(fields=['success'], name='whatsapp_in_success_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcontext',
            index=models.Index(fields=['phone_number'], name='whatsapp_co_phone_n_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcontext',
            index=models.Index(fields=['is_active'], name='whatsapp_co_is_acti_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcontext',
            index=models.Index(fields=['updated_at'], name='whatsapp_co_updated_123456_idx'),
        ),
    ] 