# Generated by Django 5.2.3 on 2024-01-01 12:00:00

import uuid
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text="User's phone number", max_length=20, unique=True)),
                ('first_name', models.CharField(blank=True, help_text="User's first name", max_length=100)),
                ('last_name', models.CharField(blank=True, help_text="User's last name", max_length=100)),
                ('email', models.EmailField(blank=True, help_text="User's email address", max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Whether user is active')),
                ('last_interaction', models.DateTimeField(default=django.utils.timezone.now, help_text='Last interaction time')),
                ('interaction_count', models.IntegerField(default=0, help_text='Total number of interactions')),
                ('preferred_language', models.CharField(default='es', help_text='User preferred language', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp User',
                'verbose_name_plural': 'WhatsApp Users',
                'db_table': 'whatsapp_users',
                'ordering': ['-last_interaction'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppInteractionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text="User's phone number", max_length=20)),
                ('message_text', models.TextField(help_text='Incoming message text')),
                ('intent_detected', models.CharField(blank=True, help_text='Detected user intent', max_length=100)),
                ('template_used', models.CharField(blank=True, help_text='Template used for response', max_length=100)),
                ('response_text', models.TextField(blank=True, help_text='Response text sent')),
                ('response_id', models.CharField(blank=True, help_text='ACS response ID', max_length=100)),
                ('parameters_used', models.JSONField(default=dict, help_text='Parameters used in template')),
                ('fallback_used', models.BooleanField(default=False, help_text='Whether OpenAI fallback was used')),
                ('processing_time_ms', models.FloatField(default=0.0, help_text='Response processing time')),
                ('success', models.BooleanField(default=True, help_text='Whether interaction was successful')),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed')),
                ('context_data', models.JSONField(default=dict, help_text='Additional context data')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'WhatsApp Interaction Log',
                'verbose_name_plural': 'WhatsApp Interaction Logs',
                'db_table': 'whatsapp_interaction_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppEventGridLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(help_text='Event Grid event ID', max_length=100)),
                ('event_type', models.CharField(help_text='Event Grid event type', max_length=100)),
                ('event_time', models.DateTimeField(help_text='Event timestamp')),
                ('data', models.JSONField(help_text='Complete event data')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'WhatsApp Event Grid Log',
                'verbose_name_plural': 'WhatsApp Event Grid Logs',
                'db_table': 'whatsapp_event_grid_logs',
                'ordering': ['-created_at'],
            },
        ),
        # Índices con nombres únicos para evitar conflictos
        migrations.AddIndex(
            model_name='whatsappuser',
            index=models.Index(fields=['phone_number'], name='whatsapp_us_phone_n_fixed_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappuser',
            index=models.Index(fields=['is_active'], name='whatsapp_us_is_acti_fixed_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappuser',
            index=models.Index(fields=['last_interaction'], name='whatsapp_us_last_in_fixed_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappuser',
            index=models.Index(fields=['interaction_count'], name='whatsapp_us_interac_fixed_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappinteractionlog',
            index=models.Index(fields=['phone_number'], name='whatsapp_in_phone_n_fixed_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappinteractionlog',
            index=models.Index(fields=['created_at'], name='whatsapp_in_created_fixed_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappinteractionlog',
            index=models.Index(fields=['intent_detected'], name='whatsapp_in_intent_fixed_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappinteractionlog',
            index=models.Index(fields=['success'], name='whatsapp_in_success_fixed_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappinteractionlog',
            index=models.Index(fields=['template_used'], name='whatsapp_in_templat_fixed_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappeventgridlog',
            index=models.Index(fields=['event_id'], name='whatsapp_ev_event_i_fixed_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappeventgridlog',
            index=models.Index(fields=['event_type'], name='whatsapp_ev_event_t_fixed_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappeventgridlog',
            index=models.Index(fields=['event_time'], name='whatsapp_ev_event_ti_fixed_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappeventgridlog',
            index=models.Index(fields=['created_at'], name='whatsapp_ev_created_fixed_idx'),
        ),
    ] 