# Generated by Django 5.2.3 on 2025-07-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("whatsapp_bot", "0002_event_grid_tables_fixed"),
    ]

    operations = [
        # Los modelos ya fueron eliminados en la migración anterior
        # Solo mantener las operaciones que no dependen de modelos eliminados
        migrations.RenameIndex(
            model_name="whatsappcontext",
            new_name="whatsapp_co_phone_n_15dd1a_idx",
            old_name="whatsapp_co_phone_n_123456_idx",
        ),
        migrations.RenameIndex(
            model_name="whatsappcontext",
            new_name="whatsapp_co_is_acti_dcdb30_idx",
            old_name="whatsapp_co_is_acti_123456_idx",
        ),
        migrations.RenameIndex(
            model_name="whatsappcontext",
            new_name="whatsapp_co_updated_d62b7a_idx",
            old_name="whatsapp_co_updated_123456_idx",
        ),
        migrations.RenameIndex(
            model_name="whatsappinteraction",
            new_name="whatsapp_in_phone_n_dcc63f_idx",
            old_name="whatsapp_in_phone_n_123456_idx",
        ),
        migrations.RenameIndex(
            model_name="whatsappinteraction",
            new_name="whatsapp_in_created_274e79_idx",
            old_name="whatsapp_in_created_123456_idx",
        ),
        migrations.RenameIndex(
            model_name="whatsappinteraction",
            new_name="whatsapp_in_templat_3110dd_idx",
            old_name="whatsapp_in_templat_123456_idx",
        ),
        migrations.RenameIndex(
            model_name="whatsappinteraction",
            new_name="whatsapp_in_success_5bf51b_idx",
            old_name="whatsapp_in_success_123456_idx",
        ),
        migrations.AddField(
            model_name="whatsapptemplate",
            name="channel_id",
            field=models.CharField(
                default="c3dd072b-92b3-4812-8ed0-10b1d3a45da1",
                help_text="ACS Channel ID",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="whatsapptemplate",
            name="language",
            field=models.CharField(
                default="es_MX", help_text="Template language code", max_length=10
            ),
        ),
    ]
