# Generated by Django 5.2.3 on 2025-07-20 22:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("whatsapp_bot", "0003_delete_whatsappdeliveryreport_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WhatsAppEventGridLog",
        ),
        migrations.DeleteModel(
            name="WhatsAppInteractionLog",
        ),
        migrations.DeleteModel(
            name="WhatsAppUser",
        ),
    ]
