# Generated by Django 5.2.3 on 2025-08-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0003_update_donation_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True),
        ),
    ]
