# Generated by Django 5.2.3 on 2025-08-06 21:31

from django.db import migrations, models
import django.db.models.deletion


def set_default_email_and_username(apps, schema_editor):
    """Establecer valores por defecto para email y username"""
    CustomUser = apps.get_model('core', 'CustomUser')
    for user in CustomUser.objects.all():
        if not user.email:
            user.email = f"user_{user.id}@example.com"
        if not user.username:
            user.username = user.email.split('@')[0]
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_customuser_email_alter_customuser_username"),
    ]

    operations = [
        # Primero establecer valores por defecto
        migrations.RunPython(set_default_email_and_username, reverse_code=migrations.RunPython.noop),
        
        # Luego hacer los campos no nullable
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(verbose_name='correo electrónico', unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(verbose_name='nombre de usuario', max_length=150, blank=True, null=True),
        ),
    ]
