# Generated by Django 5.2.3 on 2025-08-06 21:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_auto_20250806_1531"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
