# Generated by Django 4.2.7 on 2025-08-08 16:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_document_metadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="processing_status",
        ),
        migrations.AddField(
            model_name="document",
            name="processing_state",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("converting", "Convirtiendo"),
                    ("indexing", "Indexando"),
                    ("ready", "Listo"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=32,
                verbose_name="Estado de procesamiento",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="vector_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, verbose_name="ID del vector"
            ),
        ),
        migrations.CreateModel(
            name="DocumentVectorCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenido extraído")),
                (
                    "vector_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="ID del vector"
                    ),
                ),
                (
                    "last_access",
                    models.DateTimeField(auto_now=True, verbose_name="Último acceso"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vector_cache",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caché de vector de documento",
                "verbose_name_plural": "Caché de vectores de documentos",
                "db_table": "documents_vector_cache",
            },
        ),
    ]
