# Generated by Django 4.2.7 on 2025-08-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_remove_document_processing_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="vector_id",
        ),
        migrations.AlterField(
            model_name="document",
            name="processing_state",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("converting", "Convirtiendo"),
                    ("indexing", "Indexando"),
                    ("ready", "Listo"),
                    ("error", "Error"),
                ],
                db_column="processing_status",
                default="pending",
                max_length=32,
                verbose_name="Estado de procesamiento",
            ),
        ),
        migrations.DeleteModel(
            name="DocumentVectorCache",
        ),
    ]
