# Generated by Django 5.2.3 on 2025-07-19 17:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Embedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Original text content that was embedded"
                    ),
                ),
                (
                    "embedding_vector",
                    models.JSONField(help_text="Vector representation of the text"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata for the embedding",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("event", "Event"),
                            ("contact", "Contact"),
                            ("donation", "Donation"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        help_text="Type of source content",
                        max_length=50,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the source object (document, event, etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Creation timestamp",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this embedding is active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this embedding",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Embedding",
                "verbose_name_plural": "Embeddings",
                "db_table": "embeddings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source_type", "source_id"],
                        name="embeddings_source__716927_idx",
                    ),
                    models.Index(
                        fields=["created_by"], name="embeddings_created_cf0bce_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="embeddings_is_acti_89b84c_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="embeddings_created_ddac62_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmbeddingSearchLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query_text", models.TextField(help_text="Search query text")),
                (
                    "query_vector",
                    models.JSONField(help_text="Vector representation of the query"),
                ),
                (
                    "results_count",
                    models.IntegerField(
                        default=0, help_text="Number of results returned"
                    ),
                ),
                (
                    "search_time_ms",
                    models.FloatField(
                        default=0.0, help_text="Search execution time in milliseconds"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="Search timestamp"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional search metadata"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the search",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="embedding_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Embedding Search Log",
                "verbose_name_plural": "Embedding Search Logs",
                "db_table": "embedding_search_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="embedding_s_user_id_702220_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="embedding_s_created_95d04b_idx"
                    ),
                    models.Index(
                        fields=["results_count"], name="embedding_s_results_affcb9_idx"
                    ),
                ],
            },
        ),
    ]
